### ISSUE TITLE
艦娘一覧において、タブでグループを切り替えた場合はフィルターが機能しない。

### ISSUE THREAD

**Issue by tarookun** [sanaehirotaka/logbook#12]
2016-04-01の艦これアップデート以降、
艦娘一覧において、タブでグループを切り替えている場合はフィルターが機能しません。
これはフリーワード・艦種・その他(装備・艦隊～・鍵～)を問わずです。
フィルターウィンドウからグループを切り替えている場合は問題ないようです。
![7f88550f891e26004605a91c3755c43a_](https://cloud.githubusercontent.com/assets/11954548/14206670/b54d0316-f84f-11e5-80c3-fec70fecdbbd.png)

**Comment by sanaehirotaka** [comment]
報告ありがとうございます
フィルターウインドウはそれを開いた時のタブに紐付いているためタブを切り替える場合はまた開き直す必要があります。
面倒ですがタブ切り替え後にフィルターウインドウを開きなおすと機能するはずです。

**Comment by tarookun** [comment]
返信ありがとうございます。
フィルターウィンドウを開きなおすとフィルターが機能することを確認しました。
対応方法がわかり、また、大変な手間という訳でないのでこの件はcloseさせていただきます。
